name: ESP-IDF Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build project for esp32s3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: 'v5.4.1'
          target: 'esp32s3'
          path: '.'
